### ISSUE TITLE
Typing trainer moves onto next line before newline is entered

### ISSUE THREAD

**Issue by joeltimothyoh** [touchtypie/touchtypie#265]
# Issue

Typing trainer moves onto next line before newline is entered.

# Expectation

Typing trainer remains on present line until newline is entered.

# Discussion

### Before typing `.`

![image](https://user-images.githubusercontent.com/24771499/128646893-a20e72a1-d34b-4955-803b-45591849b695.png)

### After typing `.` but before typing `ENTER`

![image](https://user-images.githubusercontent.com/24771499/128646956-f195fdf1-9067-4b91-aa08-0e12efb5725c.png)

## Analysis

Instead of moving to the next line before typing `ENTER`, a symbol `↵` should be added at the end of typing trainer's string instead of moving on to the next line, hiding the present one, and displaying the cursor in front of the next line but before its first character.

![image](https://user-images.githubusercontent.com/24771499/128647170-6819ff88-204f-4394-8743-35e1d249bf5d.png)

Also, Bible verses are quite often within the same paragraph. With the present design it's difficult to distinguish a paragraph from a line break.

Related to this is the warmup where it did not come across as intuitive that it was necessary to type the `ENTER` key after the `Z` character but before the `a` character.

![image](https://user-images.githubusercontent.com/24771499/128647207-6bab6c63-5728-445f-a173-6d582fc89da3.png)

## Suggestion(s)

I think any of the following could be implemented:

* A visual representation of the `Enter` key with a visual indication that should be typed
* A revision in design of the typing trainer's display in making clear the next line is a new paragraph rather than a continuation of the previous.

**Comment by leojonathanoh** [comment]
@joeltimothyoh Ive thought of this before, while it appears intuitive to think of a newline cursor being at the end of a line, in practice one might get confused because it might appear like a space character.

Think of it this way: 

- If you already know the text, it's easy to think that a newline should be at the end
- But if you don't know the text, you might think the cursor signals a newline.

Hence it deliberate that a newline is shown to be at the beginning of a line. In fact it adds to expectability and readability, especially when u practice text which are not predictable (i.e. not sentences, e.g. code for instance).

In fact, thinking of a newline as a begining of a line, is consistent with the way unix thinks of newlines. A newline is a delimiter that indicates a beginning of an upcoming line, not the end of a line.

**Comment by leojonathanoh** [comment]
i think i might have to make it more apparent when there's a newline, by showing a symbol to the left of the new line

**Comment by joeltimothyoh** [comment]
> In fact, thinking of a newline as a begining of a line, is consistent with the way unix thinks of newlines. A newline is a delimiter that indicates a beginning of an upcoming line, not the end of a line.

Regardless, the view should not move on to the next line until typed, akin to cursors staying in place and moving onto the start of a newline only when a newline character is issued.

I think it could be helpful to keep the former line in view but perhaps faded out. That way the typist is able to retain some past context even whilst typing the present line. @l

**Comment by leojonathanoh** [comment]
>  Regardless, the view should not move on to the next line until typed, akin to cursors staying in place and moving onto the start of a newline only when a newline character is issued.

This is not difficult to make, i simply replace a newline with a ↵ symbol.

> I think it could be helpful to keep the former line in view but perhaps faded out. That way the typist is able to retain some past context even whilst typing the present line. @leojonathanoh

This one might not be that easy to implement because then there is a history buffer. Im not sure if is needed because the user can easily scroll the text upwards to see previous lines.

@joeltimothyoh

**Comment by joeltimothyoh** [comment]
> This one might not be that easy to implement because then there is a history buffer. Im not sure if is needed because the user can easily scroll the text upwards to see previous lines.

But they would be touch-typing. Context is also important in maintaining positioning and flow. @leojonathanoh

**Comment by leojonathanoh** [comment]
> > This one might not be that easy to implement because then there is a history buffer. Im not sure if is needed because the user can easily scroll the text upwards to see previous lines.
> 
> But they would be touch-typing. Context is also important in maintaining positioning and flow. @leojonathanoh

opened #268
