### ISSUE TITLE
Trainer's cursor continuous fading animation is distracting

### ISSUE THREAD

**Issue by joeltimothyoh** [touchtypie/touchtypie#267]
# Issue

Trainer's cursor continuous fading animation is distracting.

# Expectation

Trainer's cursor animation should not distract but facilitate typing.

# Discussion

As of the present design, the Trainer's cursor continuously fades in and out even while typing is occurring. The animation induces a perception that keys were successfully typed when the cursor moves onto the next key while its color is closer to white, while inducing a perception that keys were possibly mistyped when the cursor moves onto the next key while its color is closer to transparent white.

While the animation gives life to the application as well as drawing attention to the next key to type, the continuous fading in and outs induces incorrect real-time assumptions of typing accuracy, possibly contributing to cognitive fatigue, and negatively impacting typing performance.

# Suggestion

Keep the cursor solid white with minimal or no animation.

**Comment by leojonathanoh** [comment]
@joeltimothyoh i never found it fatiguing to have the fading animation, but i will try without fading to see if i actually type and focus better.
