### ISSUE TITLE
Excessive number of non-alphanumerical characters occur repeatedly before certain words

### ISSUE THREAD

**Issue by joeltimothyoh** [touchtypie/touchtypie#272]
# Issue

Excessive number of non-alphanumerical characters occur repeatedly with certain words.

# Expectation

An even distribution of non-alphanumerical characters that don't occur repeatedly with certain words

# Discussion

An example is the following where the phrase `` `is' `` repeatedly shows up. I'm unsure what it is about the word in YLT that those special characters repeatedly appear with it.

![image](https://user-images.githubusercontent.com/24771499/130719127-72aca350-2cdd-4bf2-8445-2bc8d3b9d9a1.png)

**Comment by leojonathanoh** [comment]
@joeltimothyoh this is a WYSIWYG, so if you see certain characters, those are actually present in the actual text.

As to why this is so in the YLT, somehow this version of YLT from my [bible_databases](https://github.com/leojonathanoh/bible_databases) uses backticks to encose speech expressions and square-bracketed expressions `[ xxx ]`. In the case of `is` being wrapped in backticks (i.e. square-brackets), Young meant that the original word did not appear in the hebrew, but it's added for English grammar sake. (This is what i believe, i could be wrong).

**Comment by leojonathanoh** [comment]
closing.
