### ISSUE TITLE
Display the `Start typing . . .` placeholder only when the Student response text area is unlocked

### ISSUE THREAD

**Issue by joeltimothyoh** [touchtypie/touchtypie#278]
# Issue

The `Start typing . . .`  placeholder is displayed in the Student response text area during the `Get ready . . .` stage while the Student response text area is still locked.

# Expectation

The  `Start typing . . .`  placeholder is displayed in the Student response text area after the `Get ready . . .` stage when the Student response text area is unlocked.

# Discussion

Presently, the `Start typing . . .`  placeholder is displayed during the `Get ready . . .` stage, incorrectly indicating to the Student that the Student response text area is unlocked while it is still locked. Instead,  the `Start typing . . .`  placeholder should only be displayed after the `Get ready . . .` stage when the Student response text area is unlocked, correctly indicating to the Student that they are able to respond within the Student response text area.

![image](https://user-images.githubusercontent.com/24771499/209437250-2953f07a-ce90-4c96-9cb7-9eaf6911e30f.png)

Suggestions:

1. The Student's response text area could start out greyed out during the  `Get ready . . .` stage while fading out in time to have the `Start typing . . .` placeholder displayed to the Student.
1. The `Get ready . . .`  is horizontally and vertically center aligned between the Trainer speech and Student response text areas while fading out in time to display both the Trainer speech text and Student response text areas with the `Start typing . . .`  placeholder displayed to the Student.

**Comment by leojonathanoh** [comment]
How about remove the `textarea` (i.e. `perfection` on by default). That means no more amends allowed. That way the UI is cleaner and simpler for anyone to understand.

**Comment by joeltimothyoh** [comment]
I think like presently having `perfection` either on or off is better. Maybe `perfection` could be enabled by default. Nonetheless when set to on with settings saved despite a page refresh, the `Start typing . . .` placeholder should only be displayed to the Student only when the Student response text area is unlocked. @leojonathanoh

**Comment by leojonathanoh** [comment]
Ok, keep the existing then. It is trivial to add the placeholder fix. 

As for center aligning the `Start typing . . .` it will need its own component. Right now it's simply piggybagging on the trainer's speech.
